# Generated by Django 5.0.4 on 2024-06-02 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Album', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album_model',
            name='musician_model',
        ),
    ]
