# Generated by Django 5.1.2 on 2024-11-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SishirDB', '0004_alter_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
