# Generated by Django 5.1.2 on 2024-11-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SishirDB', '0005_alter_user_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=255)),
                ('meal_description', models.TextField()),
            ],
        ),
    ]
