# Generated by Django 5.1.2 on 2024-11-18 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Brand_App', '0002_brand_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='car',
        ),
    ]
