# Generated by Django 5.1.2 on 2024-11-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_remove_author_created_at_remove_author_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.CharField(max_length=201, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='phone',
            field=models.CharField(max_length=18, null=1),
        ),
    ]
