# Generated by Django 5.1.2 on 2024-12-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Library_App', '0003_borrow_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='is_returned',
            field=models.BooleanField(default=False, null=1),
            preserve_default=1,
        ),
    ]
