# Generated by Django 5.0.4 on 2024-06-02 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Album', '0002_remove_album_model_musician_model'),
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician_model',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Album.album_model'),
        ),
    ]
