# Generated by Django 5.1.2 on 2024-11-10 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Album', '0002_remove_album_model_musician_model'),
        ('musician', '0002_musician_model_album'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musician_model',
            old_name='Instrument_type',
            new_name='instrument_type',
        ),
        migrations.AlterField(
            model_name='musician_model',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='musicians', to='Album.album_model'),
        ),
    ]
