# Generated by Django 5.1.2 on 2024-11-10 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0004_rename_instrument_type_musician_model_instrument_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musician_model',
            old_name='instrument_types',
            new_name='instrument_type',
        ),
    ]
