# Generated by Django 5.1.2 on 2024-11-18 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CurHub_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='brand',
        ),
    ]
