# Generated by Django 5.1.2 on 2024-11-18 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brand_App', '0003_remove_brand_car'),
        ('CurHub_App', '0002_remove_car_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(null=1, on_delete=django.db.models.deletion.CASCADE, related_name='car', to='Brand_App.brand'),
            preserve_default=1,
        ),
    ]
